#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"


source ~/.nvm/nvm.sh

export NVM_DIR="/Users/tim/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
